
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#include "panel-typebuiltins.h"

/* enumerations from "panel-enums-gsettings.h" */
#include "panel-enums-gsettings.h"
static const GEnumValue _panel_object_pack_type_values[] = {
  { PANEL_OBJECT_PACK_START, "PANEL_OBJECT_PACK_START", "start" },
  { PANEL_OBJECT_PACK_CENTER, "PANEL_OBJECT_PACK_CENTER", "center" },
  { PANEL_OBJECT_PACK_END, "PANEL_OBJECT_PACK_END", "end" },
  { 0, NULL, NULL }
};

GType
panel_object_pack_type_get_type (void)
{
  static GType type = 0;

  if (!type)
    type = g_enum_register_static ("PanelObjectPackType", _panel_object_pack_type_values);

  return type;
}
static const GEnumValue _panel_orientation_values[] = {
  { PANEL_ORIENTATION_TOP, "PANEL_ORIENTATION_TOP", "top" },
  { PANEL_ORIENTATION_RIGHT, "PANEL_ORIENTATION_RIGHT", "right" },
  { PANEL_ORIENTATION_BOTTOM, "PANEL_ORIENTATION_BOTTOM", "bottom" },
  { PANEL_ORIENTATION_LEFT, "PANEL_ORIENTATION_LEFT", "left" },
  { 0, NULL, NULL }
};

GType
panel_orientation_get_type (void)
{
  static GType type = 0;

  if (!type)
    type = g_enum_register_static ("PanelOrientation", _panel_orientation_values);

  return type;
}
static const GEnumValue _panel_animation_speed_values[] = {
  { PANEL_ANIMATION_SLOW, "PANEL_ANIMATION_SLOW", "slow" },
  { PANEL_ANIMATION_MEDIUM, "PANEL_ANIMATION_MEDIUM", "medium" },
  { PANEL_ANIMATION_FAST, "PANEL_ANIMATION_FAST", "fast" },
  { 0, NULL, NULL }
};

GType
panel_animation_speed_get_type (void)
{
  static GType type = 0;

  if (!type)
    type = g_enum_register_static ("PanelAnimationSpeed", _panel_animation_speed_values);

  return type;
}
static const GEnumValue _panel_background_image_style_values[] = {
  { PANEL_BACKGROUND_IMAGE_STYLE_NONE, "PANEL_BACKGROUND_IMAGE_STYLE_NONE", "none" },
  { PANEL_BACKGROUND_IMAGE_STYLE_STRETCH, "PANEL_BACKGROUND_IMAGE_STYLE_STRETCH", "stretch" },
  { PANEL_BACKGROUND_IMAGE_STYLE_FIT, "PANEL_BACKGROUND_IMAGE_STYLE_FIT", "fit" },
  { 0, NULL, NULL }
};

GType
panel_background_image_style_get_type (void)
{
  static GType type = 0;

  if (!type)
    type = g_enum_register_static ("PanelBackgroundImageStyle", _panel_background_image_style_values);

  return type;
}
static const GEnumValue _panel_theme_variant_values[] = {
  { PANEL_THEME_VARIANT_SYSTEM, "PANEL_THEME_VARIANT_SYSTEM", "system" },
  { PANEL_THEME_VARIANT_LIGHT, "PANEL_THEME_VARIANT_LIGHT", "light" },
  { PANEL_THEME_VARIANT_DARK, "PANEL_THEME_VARIANT_DARK", "dark" },
  { 0, NULL, NULL }
};

GType
panel_theme_variant_get_type (void)
{
  static GType type = 0;

  if (!type)
    type = g_enum_register_static ("PanelThemeVariant", _panel_theme_variant_values);

  return type;
}

/* enumerations from "panel-types.h" */
#include "panel-types.h"
static const GEnumValue _panel_speed_values[] = {
  { PANEL_SPEED_SLOW, "PANEL_SPEED_SLOW", "slow" },
  { PANEL_SPEED_MEDIUM, "PANEL_SPEED_MEDIUM", "medium" },
  { PANEL_SPEED_FAST, "PANEL_SPEED_FAST", "fast" },
  { 0, NULL, NULL }
};

GType
panel_speed_get_type (void)
{
  static GType type = 0;

  if (!type)
    type = g_enum_register_static ("PanelSpeed", _panel_speed_values);

  return type;
}

/* Generated data ends here */

