
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#ifndef __CLOCK_TYPEBUILTINS_H__
#define __CLOCK_TYPEBUILTINS_H__ 1

G_BEGIN_DECLS
G_END_DECLS

#endif /* __CLOCK_TYPEBUILTINS_H__ */

/* Generated data ends here */

